  apiVersion: monitoring.coreos.com/v1
  kind: Prometheus
  metadata:
    labels:
      prometheus: k8s
    name: msday2020-prometheus-cluster
    namespace: msday2020\
  spec:
    replicas: 1
    ruleSelector:
      matchLabels:
        prometheus: example
    securityContext: {}
    serviceAccountName: prometheus-k8s
    serviceMonitorSelector:
      matchLabels:
        k8s-app: prometheus
