apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    k8s-app: prometheus
  name: service-monitor
spec:
  endpoints:
    - interval: 1s
      path: /actuator/prometheus
      port: http
  selector:
    matchLabels:
      k8s-app: prometheus
