kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: prometheus
  labels:
    operated-prometheus: 'true'
spec:
  host: ""
  to:
    kind: Service
    name: prometheus-operated
    weight: 100
  port:
    targetPort: web
  wildcardPolicy: None
status:
  ingress:
    - host: ""