kind: ImageStream
apiVersion: image.openshift.io/v1
metadata:
  annotations:
    {{- include "spring-boot.annotations" . | nindent 4 }}
  name: {{ .Chart.Name }}
  labels:
    {{- include "spring-boot.labels" . | nindent 4 }}
spec:
  lookupPolicy:
    local: false