apiVersion: v1
entries:
  monitor-app:
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2020-05-13T12:48:43.1252043-04:00"
    dependencies:
    - alias: thermostat-service
      name: spring-boot
      repository: file://../spring-boot
      version: 0.1.3
    - alias: temperature-processor
      name: spring-boot
      repository: file://../spring-boot
      version: 0.1.3
    - alias: prometheus-receiver
      name: spring-boot
      repository: file://../spring-boot
      version: 0.1.3
    description: A Helm chart to deploy a Spring Boot application from a git repository
    digest: cb870810084becfed713bc38524b9607fef6bf43b0e519b629eee9030cb840c3
    name: monitor-app
    type: application
    urls:
    - monitor-app-0.1.1.tgz
    version: 0.1.1
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2020-05-13T12:48:43.1232046-04:00"
    dependencies:
    - alias: thermostat-service
      name: spring-boot
      repository: file://../spring-boot
      version: 0.1.2
    - alias: temperature-processor
      name: spring-boot
      repository: file://../spring-boot
      version: 0.1.2
    - alias: prometheus-receiver
      name: spring-boot
      repository: file://../spring-boot
      version: 0.1.2
    description: A Helm chart to deploy a Spring Boot application from a git repository
    digest: f810831e6d12a1463d8f3216508da0e03861972d9579dd614702d194eb358c94
    name: monitor-app
    type: application
    urls:
    - monitor-app-0.1.0.tgz
    version: 0.1.0
  spring-boot:
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2020-05-13T12:48:43.1262457-04:00"
    description: A Helm chart to deploy a Spring Boot application from a git repository
    digest: 5ac957ea6ca111cc6f8dd02c1f569c00e06569dae505f22ae929097670a502b7
    name: spring-boot
    type: application
    urls:
    - charts/spring-boot-0.1.3.tgz
    version: 0.1.3
generated: "2020-05-13T12:48:43.119238-04:00"
